CREATE TABLE dbo.TipoInquilino
(
IdTipoInquilino INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_TipoInquilino PRIMARY KEY CLUSTERED(IdTipoInquilino)
,Descripcion VARCHAR(250) NOT NULL
,Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION = PAGE)
GO